CREATE DATABASE IF NOT EXISTS estoquecarros;

CREATE TABLE loja (
	id BIGINT NOT NULL AUTO_INCREMENT,
    nome VARCHAR(255) NOT NULL,
    endereco VARCHAR(255) NOT NULL,
    telefone BIGINT(14) NOT NULL,
    PRIMARY KEY(id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE carro (
	id BIGINT NOT NULL AUTO_INCREMENT,
    marca VARCHAR(255) NOT NULL,
    modelo VARCHAR(255) NOT NULL,
    ano BIGINT(4),
    cor VARCHAR(25),
    placa VARCHAR(10) UNIQUE NOT NULL,
    loja_id BIGINT NOT NULL,
    FOREIGN KEY(loja_id) REFERENCES loja(id),
    PRIMARY KEY(id)    
)ENGINE=InnoDB DEFAULT CHARSET=utf8;